name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y z80asm make

      - name: Run Makefile
        working-directory: ./assembly
        run: make

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello_world_bin
          path: assembly/hello_world.bin
