name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt install -y z80asm make
    - name: Run Makefile
      working-directory: ./assembly
      run: make
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: hello_world.bin
        path: assembly/hello_world.bin